name: Pull request template
description: Describe PR.

body:
  - type: markdown
    attributes:
      value: "## Pull Request Infos"
  - type: textarea
    attributes:
      label: Describe the PR
      description: A clear and concise description of what the PR is.
      placeholder: Tell us what you make!
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: PR Type
      options:
        - label: "`Add:` Add feature or enhanced."
        - label: "`Fix:` Bug fix or change default values."
        - label: "`Clean:` Refactoring."
        - label: "`Doc:` Update docs."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related Issue
      description: |
        Related or discussed issues.

        If it's a big change, it's a good idea to open an issue ahead of time.
      placeholder: Put in issue link
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or video to help explain your commit.
      placeholder: Drag or paste images or videos to upload
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the commit here.
      placeholder: Anything to write down or refer to is fine
    validations:
      required: false
